Add private headers
After the commit(8157ecc Separate public and private enums) introduced,
there comes a race as below:
 | In file included from ../git/src/hdy-settings.c:11:
 | ../git/src/hdy-settings-private.h:16:10: fatal error: hdy-enums-private.h: No such file or directory
 |    16 | #include "hdy-enums-private.h"

So also add private headers like private sources to libhandy_sources to
fix the issue.

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>